### ISSUE TITLE
Make my own

### ISSUE THREAD

**Issue by ghost** [benbeezy/Dollo#1]
Hi !
I'm interested in your project and  would like to print a working 3D printer with your repo.
However, I'm a bit lost with all that, what are the best slicing parameters and pieces I've gotta print and how big is the biggest piece (to know if I can print it on my friend's printer).
I already read your instructable.

Thanks for answering.

**Comment by wildseyed** [comment]
@Fafadu: The largest pieces are actually made from smaller pieces that snap together.  Even a very small 3D printer will be able to print this.

**Comment by ghost** [comment]
And what about the density or slicing ? What are the best infill and layers ?

**Comment by benbeezy** [comment]
@Fafadu40 for the infill I use something around 20-25% and 2 solid layers on top bottom and 2 parameters. I think I even have a slicer config file in the git repo (not sure how up to date it is so you should check first)

**Comment by ghost** [comment]
So if I print a basic size, how much plastic do I need ?

**Comment by benbeezy** [comment]
You should be able to print everything with a one kg spool, it will use up
the entire spool though.

**Comment by ghost** [comment]
OK thanks. It's a student project so I think I'll be back there to ask some more questions :)

**Comment by benbeezy** [comment]
Feel free to ask anything you want :) im willing to answer anything. I
would say try to print the long ties directory. It looks better and is
stronger in the joints.

**Comment by ghost** [comment]
What's different with those long ties ?

**Comment by benbeezy** [comment]
If you look at the stl files I rotated the slots to go with the length
instead of across it. So it uses sliding joints now. So you can have 8
contact points where pieces join instead of just 4 I printed one out and it
is going to be the version 2 of the dollo.
