### ISSUE TITLE
Printable Bed Mount/Carriage

### ISSUE THREAD

**Issue by sarf2k4** [benbeezy/Dollo#2]
Hi, is there any considerations to have a printable bed mount/carriage instead of drilling a hole in the acrylic? 

Here is my fully printable y carriage meant to be used on prusa based structure. I believe these can be incorporated here as well

v2 - http://www.thingiverse.com/thing:1319196
v3 - http://www.thingiverse.com/thing:1345816

**Comment by spegelius** [comment]
I did some openscadding and designed a modular bed carriage, commit here: https://github.com/spegelius/Dollo/commit/90b00451724bb7ac4423c7c2c93818054710ddfc.
I did print the center piece and arm, seems to fit together. Need to print the rest to see how well the dimensions match the gears and bed itself.

**Comment by benbeezy** [comment]
These files are now merged into master so I am going to close this issue. If you have any other issues with missing models or maybe if something doesn't quite print right please feel free to open another issue
